### ISSUE TITLE
Please reformat Changelog to be parseable 

### ISSUE THREAD

**Issue by luzpaz** [JohnVictoryz/SimplePythonBrowser#7]
Currently the [Changelog](https://github.com/The-All-Python-Project/SimplePythonBrowser/wiki/Changelog) is posting version oldest to to newest. Would you consider posting the versions newest -> oldest ?

Maybe following some of the other guidelines in https://keepachangelog.com/ ?

**Comment by JohnVictoryz** [comment]
OK fixed it just to let you know i am not too much working on this although sometimes i try to do something here and there to make this better
